import {
    FolderRoot, AlertTriangle, AlertCircle, UserCircle as RatioIcon, 
    UserCircle as UserCircleIcon, Badge as BadgeIcon, Compass as NavigationIcon, 
    Square, MousePointerClick, Calendar, CreditCard, 
    GalleryHorizontal as GalleryHorizontalIcon, Box, CheckSquare as CheckSquareIcon, 
    ChevronDown as ChevronDownIcon, Terminal as TerminalIcon, Command as CommandIcon, 
    Menu as MenuIcon, Table, RectangleHorizontal, PanelTop as PanelTopIcon, 
    ChevronDown, Circle as CircleIcon, FileText, FileInput as FileInputIcon, TextCursorInput, Ungroup, Shield, Keyboard, Tag as TagIcon, 
    Menu, Compass as CompassIcon, ListOrdered, Popcorn, Minus as MinusIcon, 
    Radio as BoomBox, GripVertical, Mouse, LassoSelect, Minus, 
    PanelsRightBottom, SlidersHorizontal, Bell, Loader2, ToggleLeft, 
    PanelTop, SquarePen, Eclipse, Settings2, UserCircle, WandIcon, ComponentIcon, SidebarIcon, LayoutDashboardIcon, MessageCircleIcon, FileTextIcon
  } from "lucide-react";
  
// Category configuration with icons
export const categoryConfig: Record<
  string,
  { icon: React.FC; label?: string }
> = {
  ai: { icon: WandIcon, label: "AI" },
  ui: { icon: ComponentIcon, label: "UI" },
  sidebar: { icon: SidebarIcon, label: "Sidebar" },
  dashboards: { icon: LayoutDashboardIcon, label: "Dashboards" },
  chat: { icon: MessageCircleIcon, label: "Chat" },
  page: { icon: FileTextIcon, label: "Page" },
}
type ComponentConfig = {
  name: string
  component: React.ComponentType | null
  className?: string
  type: "registry:ui" | "registry:page" | "registry:block"
  href: string
  label?: string
  icon?: React.FC
  category?: string
}

// Category configuration with icons
  export const componentRegistry: Record<string, ComponentConfig> = {
    accordion: {
      name: "Accordion",
      component: null,
      type: "registry:ui",
      href: "/sidebar/accordion",
      category: "ui",
      icon: FolderRoot,
    },
    alert: {
      name: "Alert",
      component: null,
      type: "registry:ui",
      href: "/sidebar/alert",
      category: "ui",
      icon: AlertTriangle,
    },
    "alert-dialog": {
      name: "Alert Dialog",
      component: null,
      type: "registry:ui",
      href: "/sidebar/alert-dialog",
      category: "ui",
      icon: AlertCircle,
    },
    "aspect-ratio": {
      name: "Aspect Ratio",
      component: null,
      type: "registry:ui",
      href: "/sidebar/aspect-ratio",
      category: "ui",
      icon: RatioIcon,
    },
    avatar: {
      name: "Avatar",
      component: null,
      type: "registry:ui",
      href: "/sidebar/avatar",
      category: "ui",
      icon: UserCircleIcon,
    },
    badge: {
      name: "Badge",
      component: null,
      type: "registry:ui",
      href: "/sidebar/badge",
      category: "ui",
      icon: BadgeIcon,
    },
    breadcrumb: {
      name: "Breadcrumb",
      component: null,
      type: "registry:ui",
      href: "/sidebar/breadcrumb",
      category: "ui",
      icon: NavigationIcon,
    },
    button: {
      name: "Button",
      component: null,
      type: "registry:ui",
      href: "/sidebar/button",
      category: "ui",
      icon: Square,
    },
    "button-group": {
      name: "Button Group",
      component: null,
      type: "registry:ui",
      href: "/sidebar/button-group",
      label: "New",
      category: "ui",
      icon: MousePointerClick,
    },
    calendar: {
      name: "Calendar",
      component: null,
      type: "registry:ui",
      href: "/sidebar/calendar",
      category: "ui",
      icon: Calendar,
    },
    card: {
      name: "Card",
      component: null,
      type: "registry:ui",
      href: "/sidebar/card",
      category: "ui",
      icon: CreditCard,
    },
    carousel: {
      name: "Carousel",
      component: null,
      type: "registry:ui",
      href: "/sidebar/carousel",
      category: "ui",
      icon: GalleryHorizontalIcon,
    },
    chart: {
      name: "Chart",
      component: null,
      className: "w-full",
      type: "registry:ui",
      href: "/sidebar/chart",
      category: "ui",
      icon: Box,
    },
    checkbox: {
      name: "Checkbox",
      component: null,
      type: "registry:ui",
      href: "/sidebar/checkbox",
      category: "ui",
      icon: CheckSquareIcon,
    },
    collapsible: {
      name: "Collapsible",
      component: null,
      type: "registry:ui",
      href: "/sidebar/collapsible",
      category: "ui",
      icon: ChevronDownIcon,
    },
    combobox: {
      name: "Combobox",
      component: null,
      type: "registry:ui",
      href: "/sidebar/combobox",
      category: "ui",
      icon: TerminalIcon,
    },
    command: {
      name: "Command",
      component: null,
      type: "registry:ui",
      href: "/sidebar/command",
      category: "ui",
      icon: CommandIcon,
    },
    "context-menu": {
      name: "Context Menu",
      component: null,
      type: "registry:ui",
      href: "/sidebar/context-menu",
      category: "ui",
      icon: MenuIcon,
    },
    "date-picker": {
      name: "Date Picker",
      component: null,
      type: "registry:ui",
      href: "/sidebar/date-picker",
      category: "ui",
      icon: Calendar,
    },
    dialog: {
      name: "Dialog",
      component: null,
      type: "registry:ui",
      href: "/sidebar/dialog",
      category: "ui",
      icon: RectangleHorizontal,
    },
    drawer: {
      name: "Drawer",
      component: null,
      type: "registry:ui",
      href: "/sidebar/drawer",
      category: "ui",
      icon: PanelTopIcon,
    },
    "dropdown-menu": {
      name: "Dropdown Menu",
      component: null,
      type: "registry:ui",
      href: "/sidebar/dropdown-menu",
      category: "ui",
      icon: ChevronDown,
    },
    empty: {
      name: "Empty",
      component: null,
      type: "registry:ui",
      href: "/sidebar/empty",
      label: "New",
      category: "ui",
      icon: CircleIcon,
    },
    field: {
      name: "Field",
      component: null,
      type: "registry:ui",
      href: "/sidebar/field",
      label: "New",
      category: "ui",
      icon: FileText,
    },
    form: {
      name: "Form",
      component: null,
      type: "registry:ui",
      href: "/sidebar/form",
      category: "ui",
      icon: FileInputIcon,
    },
    "hover-card": {
      name: "Hover Card",
      component: null,
      type: "registry:ui",
      href: "/sidebar/hover-card",
      category: "ui",
      icon: CreditCard,
    },
    input: {
      name: "Input",
      component: null,
      type: "registry:ui",
      href: "/sidebar/input",
      category: "ui",
      icon: TextCursorInput,
    },
    "input-group": {
      name: "Input Group",
      component: null,
      type: "registry:ui",
      href: "/sidebar/input-group",
      label: "New",
      category: "ui",
      icon: Ungroup,
    },
    "input-otp": {
      name: "Input OTP",
      component: null,
      type: "registry:ui",
      href: "/sidebar/input-otp",
      category: "ui",
      icon: Shield,
    },
    item: {
      name: "Item",
      component: null,
      type: "registry:ui",
      href: "/sidebar/item",
      label: "New",
      category: "ui",
      icon: CircleIcon,
    },
    kbd: {
      name: "Kbd",
      component: null,
      type: "registry:ui",
      href: "/sidebar/kbd",
      label: "New",
      category: "ui",
      icon: Keyboard,
    },
    label: {
      name: "Label",
      component: null,
      type: "registry:ui",
      href: "/sidebar/label",
      category: "ui",
      icon: TagIcon,
    },
    menubar: {
      name: "Menubar",
      component: null,
      type: "registry:ui",
      href: "/sidebar/menubar",
      category: "ui",
      icon: Menu,
    },
    "navigation-menu": {
      name: "Navigation Menu",
      component: null,
      type: "registry:ui",
      href: "/sidebar/navigation-menu",
      category: "ui",
      icon: CompassIcon,
    },
    "native-select": {
      name: "Native Select",
      component: null,
      type: "registry:ui",
      href: "/sidebar/native-select",
      label: "New",
      category: "ui",
      icon: ChevronDown,
    },
    pagination: {
      name: "Pagination",
      component: null,
      type: "registry:ui",
      href: "/sidebar/pagination",
      category: "ui",
      icon: ListOrdered,
    },
    popover: {
      name: "Popover",
      component: null,
      type: "registry:ui",
      href: "/sidebar/popover",
      category: "ui",
      icon: Popcorn,
    },
    progress: {
      name: "Progress",
      component: null,
      type: "registry:ui",
      href: "/sidebar/progress",
      category: "ui",
      icon: MinusIcon,
    },
    "radio-group": {
      name: "Radio Group",
      component: null,
      type: "registry:ui",
      href: "/sidebar/radio-group",
      category: "ui",
      icon: BoomBox,
    },
    resizable: {
      name: "Resizable",
      component: null,
      type: "registry:ui",
      href: "/sidebar/resizable",
      category: "ui",
      icon: GripVertical,
    },
    "scroll-area": {
      name: "Scroll Area",
      component: null,
      type: "registry:ui",
      href: "/sidebar/scroll-area",
      category: "ui",
      icon: Mouse,
    },
    select: {
      name: "Select",
      component: null,
      type: "registry:ui",
      href: "/sidebar/select",
      category: "ui",
      icon: LassoSelect,
    },
    separator: {
      name: "Separator",
      component: null,
      type: "registry:ui",
      href: "/sidebar/separator",
      category: "ui",
      icon: Minus,
    },
    sheet: {
      name: "Sheet",
      component: null,
      type: "registry:ui",
      href: "/sidebar/sheet",
      category: "ui",
      icon: PanelsRightBottom,
    },
    skeleton: {
      name: "Skeleton",
      component: null,
      type: "registry:ui",
      href: "/sidebar/skeleton",
      category: "ui",
      icon: RectangleHorizontal,
    },
    slider: {
      name: "Slider",
      component: null,
      type: "registry:ui",
      href: "/sidebar/slider",
      category: "ui",
      icon: SlidersHorizontal,
    },
    sonner: {
      name: "Sonner",
      component: null,
      type: "registry:ui",
      href: "/sidebar/sonner",
      category: "ui",
      icon: Bell,
    },
    spinner: {
      name: "Spinner",
      component: null,
      type: "registry:ui",
      href: "/sidebar/spinner",
      label: "New",
      category: "ui",
      icon: Loader2,
    },
    switch: {
      name: "Switch",
      component: null,
      type: "registry:ui",
      href: "/sidebar/switch",
      category: "ui",
      icon: ToggleLeft,
    },
    table: {
      name: "Table",
      component: null,
      type: "registry:ui",
      href: "/sidebar/table",
      category: "ui",
      icon: Table,
    },
    tabs: {
      name: "Tabs",
      component: null,
      type: "registry:ui",
      href: "/sidebar/tabs",
      category: "ui",
      icon: PanelTop,
    },
    textarea: {
      name: "Textarea",
      component: null,
      type: "registry:ui",
      href: "/sidebar/textarea",
      category: "ui",
      icon: SquarePen,
    },
    toggle: {
      name: "Toggle",
      component: null,
      type: "registry:ui",
      href: "/sidebar/toggle",
      category: "ui",
      icon: Eclipse,
    },
    "toggle-group": {
      name: "Toggle Group",
      component: null,
      type: "registry:ui",
      href: "/sidebar/toggle-group",
      category: "ui",
      icon: Settings2,
    },
    tooltip: {
      name: "Tooltip",
      component: null,
      type: "registry:ui",
      href: "/sidebar/tooltip",
      category: "ui",
      icon: UserCircle,
    },
  blocks: {
    name: "Forms",
    component: null,
    type: "registry:page",
    href: "/sidebar/forms",
  },
  "next-form": {
    name: "Next.js Form",
    component: null,
    type: "registry:page",
    href: "/sidebar/next-form",
  },
  "tanstack-form": {
    name: "Tanstack Form",
    component: null,
    type: "registry:page",
    href: "/sidebar/tanstack-form",
  },
  "react-hook-form": {
    name: "React Hook Form",
    component: null,
    type: "registry:page",
    href: "/sidebar/react-hook-form",
  },
}

export type ComponentKey = keyof typeof componentRegistry